parameters:
    pmx_rrd.rra_file_location: '/var/tmp/'
    pmx_rrd.png_file_location: '/bundles/pmxrrd/images/'

services:
    pmx_rrd.graph:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdGraph
        arguments: [%pmx_rrd.rra_file_location%]
    pmx_rrd.db:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdDatabase
        arguments: [%pmx_rrd.png_file_location%]
    pmx_rrd.twig.extension:
           class: Pmx\Bundle\RrdBundle\Twig\PmxRrdExtension
           arguments: [@service_container]
           tags:
             -  { name: twig.extension }