services:
    pmx_rrd.graph:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdGraph
        arguments: [%pmx_rrd.database_location%, %pmx_rrd.graph_location%, @service_container]

    pmx_rrd.db:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdDatabase
        arguments: ['', %pmx_rrd.database_location%]

    pmx_rrd.info:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdInfo

    pmx_rrd.twig.extension:
        class: Pmx\Bundle\RrdBundle\Twig\PmxRrdExtension
        arguments: [@service_container]
        tags:
            -  { name: twig.extension }
