parameters:
    pmx_rrd.file_location: '/var/tmp'

services:
#    pmx_rrd.example:
#        class: %pmx_rrd.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pmx_rrd.graph:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdGraph
#        arguments: [@service_id]
    pmx_rrd.db:
        class: Pmx\Bundle\RrdBundle\Component\PmxRrdDatabase
#        arguments: [@service_id]